{% set version = "0.2.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-parsnip
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/parsnip_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/parsnip/parsnip_{{ version }}.tar.gz
  sha256: 7606ebee2317be6b5b93842dcbec670470fce290b37b211a4c987f1a121b413c

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dplyr >=0.8.0.1
    - r-generics >=0.1.0
    - r-globals
    - r-glue
    - r-hardhat >=0.1.5.9000
    - r-lifecycle
    - r-magrittr
    - r-prettyunits
    - r-purrr
    - r-rlang >=0.3.1
    - r-tibble >=2.1.1
    - r-tidyr >=1.0.0
    - r-vctrs >=0.2.0
  run:
    - r-base
    - r-dplyr >=0.8.0.1
    - r-generics >=0.1.0
    - r-globals
    - r-glue
    - r-hardhat >=0.1.5.9000
    - r-lifecycle
    - r-magrittr
    - r-prettyunits
    - r-purrr
    - r-rlang >=0.3.1
    - r-tibble >=2.1.1
    - r-tidyr >=1.0.0
    - r-vctrs >=0.2.0

test:
  commands:
    - $R -e "library('parsnip')"           # [not win]
    - "\"%R%\" -e \"library('parsnip')\""  # [win]

about:
  home: https://tidymodels.github.io/parsnip, https://github.com/tidymodels/parsnip
  license: MIT
  summary: A common interface is provided to allow users to specify a model without having to remember the different argument names across different functions or computational engines (e.g. 'R', 'Spark', 'Stan', etc).
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - apcamargo
