{% set version = "0.1.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-parsnip
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/parsnip_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/parsnip/parsnip_{{ version }}.tar.gz
  sha256: ab5f5f0871f3f222f61d809d8b43ca0b5a683da5cdf579f3a399951f2a6f487c

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-dplyr >=0.8.0.1
    - r-generics
    - r-globals
    - r-glue
    - r-magrittr
    - r-prettyunits
    - r-purrr
    - r-rlang >=0.3.1
    - r-tibble >=2.1.1
    - r-tidyr
    - r-vctrs >=0.2.0
  run:
    - r-base
    - r-dplyr >=0.8.0.1
    - r-generics
    - r-globals
    - r-glue
    - r-magrittr
    - r-prettyunits
    - r-purrr
    - r-rlang >=0.3.1
    - r-tibble >=2.1.1
    - r-tidyr
    - r-vctrs >=0.2.0

test:
  commands:
    - $R -e "library('parsnip')"           # [not win]
    - "\"%R%\" -e \"library('parsnip')\""  # [win]

about:
  home: https://tidymodels.github.io/parsnip, https://github.com/tidymodels/parsnip
  license: GPL-2
  summary: A common interface is provided to allow users to specify a model without having to remember the different argument names across different functions or
    computational engines (e.g. 'R', 'Spark', 'Stan', etc).
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - apcamargo
    - conda-forge/r

# Package: parsnip
# Version: 0.0.4
# Title: A Common API to Modeling and Analysis Functions
# Description: A common interface is provided to allow users to specify a model without having to remember the different argument names across different functions or computational engines (e.g. 'R', 'Spark', 'Stan', etc).
# Authors@R: c( person(given = "Max",   family = "Kuhn",    email = "max@rstudio.com",   role = c("aut", "cre")), person(given = "Davis", family = "Vaughan", email = "davis@rstudio.com", role = c("aut")), person("RStudio", role = "cph"))
# Maintainer: Max Kuhn <max@rstudio.com>
# URL: https://tidymodels.github.io/parsnip, https://github.com/tidymodels/parsnip
# BugReports: https://github.com/tidymodels/parsnip/issues
# License: GPL-2
# Encoding: UTF-8
# LazyData: true
# ByteCompile: true
# VignetteBuilder: knitr
# Depends: R (>= 2.10)
# Imports: dplyr (>= 0.8.0.1), rlang (>= 0.3.1), purrr, utils, tibble (>= 2.1.1), generics, glue, magrittr, stats, tidyr, globals, prettyunits, vctrs (>= 0.2.0)
# RoxygenNote: 6.1.99.9001
# Suggests: testthat, knitr, rmarkdown, survival, keras, xgboost, covr, C50, sparklyr (>= 1.0.0), earth, glmnet, kernlab, kknn, randomForest, ranger, rpart, MASS, nlme
# NeedsCompilation: no
# Packaged: 2019-11-02 17:04:10 UTC; max
# Author: Max Kuhn [aut, cre], Davis Vaughan [aut], RStudio [cph]
# Repository: CRAN
# Date/Publication: 2019-11-02 17:30:02 UTC
