{% set version = "1.3.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-parsnip
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/parsnip_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/parsnip/parsnip_{{ version }}.tar.gz
  sha256: b1e10aa2452b9f805c318ceca6f51a7520e3a71d8e6b95b8e622af9fd9da05ff

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli
    - r-dplyr >=1.1.0
    - r-generics >=0.1.2
    - r-ggplot2
    - r-globals
    - r-glue
    - r-hardhat >=1.1.0
    - r-lifecycle
    - r-magrittr
    - r-pillar
    - r-prettyunits
    - r-purrr >=1.0.0
    - r-rlang >=0.3.1
    - r-tibble >=2.1.1
    - r-tidyr >=1.3.0
    - r-vctrs >=0.6.0
    - r-withr
  run:
    - r-base
    - r-cli
    - r-dplyr >=1.1.0
    - r-generics >=0.1.2
    - r-ggplot2
    - r-globals
    - r-glue
    - r-hardhat >=1.1.0
    - r-lifecycle
    - r-magrittr
    - r-pillar
    - r-prettyunits
    - r-purrr >=1.0.0
    - r-rlang >=0.3.1
    - r-tibble >=2.1.1
    - r-tidyr >=1.3.0
    - r-vctrs >=0.6.0
    - r-withr

test:
  commands:
    - $R -e "library('parsnip')"           # [not win]
    - "\"%R%\" -e \"library('parsnip')\""  # [win]

about:
  home: https://tidymodels.github.io/parsnip, https://github.com/tidymodels/parsnip
  license: MIT
  summary: A common interface is provided to allow users to specify a model without having to remember the different argument names across different functions or computational engines (e.g. 'R', 'Spark', 'Stan', etc).
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - apcamargo
