travis:
  secure:
    BINSTAR_TOKEN: haLLuRq1Hr4YGBmg/FTsxuL34SCF0kE8o1jP8ajL6n5gZHQ9VVkoivUec3Fk0VHk7xUBoQwlCnjPKkGRRj8fsuPga0/yVbSm8S1Y5eXqs48AEXzMXHt5/JVFTeEy2dpjkgdjwxRRQotBzgWiCvuH7jil5zqyKvk0sDYRXWpJooNvkmycxfOiIQ+YnfjZEzlz0hBSR9gvbxa5l2Gvvnb303mlV8JASxmMgrKmXSEGN3tYtS3m7w6WAy1EQTzKYiuv2+bBE+fOFXclHlywJArCc6RLxiDooGBjqlIxiZ0witga88i41WSUhIGPFJH+6AydFCDX6IjZvf4gHjNATaJ9F1LVCkr2noc74AHhHLgPiSTh7OX2wb9nWlaMFs0ZEV1CVFOuIz4eC7pfb15IwfoD/k9YUGvc9Qsv/CbHH6rabSyZlLhSQY6/KyePqMpxUvA5cCFYt7oArJAo1J/Nueg8QVLMknEDEWEJqkazG0PK58+tEoUqUw62GS+suVCzCMjQ9uPDVZrw5og5ASQSZaxUGwuFvA2JoKgqAbrgA7hjrTexTjjKCMtL3HVeMqpUMrUkqRFMsjW+o2W6OcXgZpwO5JSNHKpf4lTV2Nq0njSGxIx7SJ+QBEXXh5V3u+OUipj/gMnfSLI9GiapFABsUokJaIhoZAL8bsO65iqDySMYSdQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
